name: Docker Build

on:
  release:
    types: [published]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Login to DockerHub Registry
      run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
    - name: Get the version
      id: vars
      run: echo ::set-output name=tag::$(echo ${GITHUB_REF:10})
    - name: Build the versioned and the latest Docker image
      run: docker build . -t raonigabriel/theia-java:${{steps.vars.outputs.tag}} -t raonigabriel/theia-java:latest
    - name: Push the versioned Docker image
      run: docker push raonigabriel/theia-java:${{steps.vars.outputs.tag}}
    - name: Push the latest Docker image
      run: docker push raonigabriel/theia-java:latest  
